name: test pypi packages

# Controls when the action will run.
on:
  # schedual test for nightly build
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'Warning'
      tags:
        description: 'Test packages'

jobs:
  # test packages
  test:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macOS-latest]
            test: [core, extensions]
            python: [3.7,3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libopenmpi-dev openmpi-bin libsuperlu-dev libsuitesparse-dev petsc-dev paraview python3-paraview gmsh
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install gcc openmpi superlu suite-sparse petsc paraview gmsh
          fi
        shell: bash

      - name: Setup venv
        run: |
          python3 -m venv dune-env
          source dune-env/bin/activate
          pip install --upgrade pip
          pip install matplotlib scipy pygmsh petsc4py triangle
        shell: bash

      - name: Install dune modules
        run: |
          source dune-env/bin/activate
          pip install dune-fem
        shell: bash

      - name: Install extension modules
        if: ${{ matrix.test == 'extensions' }}
        run: |
          source dune-env/bin/activate
          pip install dune-fem-dg dune-vem
        shell: bash

      - name: Setup dune-py
        run: |
          source dune-env/bin/activate
          pip list
          DUNE_CONTROL_PATH=dune-env setup-dunepy.py --opts=config.opts
          python -m dune.fem tutorial
        shell: bash

      - name: Run tutorial
        run: |
          source dune-env/bin/activate
          export DUNEPY_DISABLE_PLOTTING=1
          export DUNE_LOG_LEVEL=${{ github.event.inputs.logLevel }}
          cd fem_tutorial
          python ../run-tutorial.py ${{ matrix.test }}
        shell: bash
