---
name: test tutorial
# yamllint disable rule:line-length

# Controls when the action will run.
on:        # yamllint disable-line rule:truthy
  # schedule test for nightly build
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Note: the defaults are repeated within the 'env' section
    #       of some of the jobs so any change to the default
    #       need to be done (at least) twice!
    inputs:
      runTests:
        type: boolean
        description: run testing scenarios [true]
        required: true
        default: true
      uploadNB:
        type: boolean
        description: upload new notebooks [true]
        required: true
        default: true
      download:
        type: choice
        description: 'download location ( dune | lund ) [dune]'
        required: true
        default: 'dune'
        options:
          - dune
          - github
          - lund
      branch:
        # note: this should be either 'master' or a tag of the form
        #       vN where 'N' is a legal python package version
        #       e.g. N=2.8.0rc1
        #       otherwise the distributions will not be generated
        #       and the build will fail
        description: 'core tag e.g. (master | v2.8.0) [master]'
        required: true
        default: 'master'
      fembranch:
        # note: this should be either 'master' or a tag of the form
        #       vN where 'N' is a legal python package version
        #       e.g. N=2.8.0rc1
        #       otherwise the distributions will not be generated
        #       and the build will fail
        description: 'fem tag e.g. (master | v2.8.0.1) [master]'
        required: true
        default: 'master'
      fempybranch:
        # note: this should be either 'master' or a tag of the form
        #       vN where 'N' is a legal python package version
        #       e.g. N=2.8.0rc1
        #       otherwise the distributions will not be generated
        #       and the build will fail
        description: 'fempy tag e.g. (master | v2.8.0.1) [master]'
        required: true
        default: 'master'
      testingbranch:
        # note: this should be either 'master' or a tag of the form
        #       vN where 'N' is a legal python package version
        #       e.g. N=2.8.0rc1
        #       otherwise the distributions will not be generated
        #       and the build will fail
        description: 'tag for testing repo e.g. (master | v2.8.0.1) [master]'
        required: true
        default: 'main'
      logLevel:
        type: choice
        description: 'Log level [Warning]'
        required: true
        default: 'Warning'
        options:
          - Debug
          - Warning
          - Info
          - error
      cxxFlags:
        description: 'compile flags (leave empty for default, consider -g -Werror=deprecated-declarations)'
        default: ''
      # needed only for dispatching from other repo
      distinct_id:
        required: false
        description: 'set when dispatching from external repo - leave empty'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      DOWNURL: 'https://gitlab.dune-project.org'
      # same for dune and github build, different for lund
      FEMPYGITURL: 'https://gitlab.dune-project.org/dune-fem/dune-fempy.git'
      RUNTESTS: ${{ !contains(github.event.inputs.runTests, 'false') }}
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        if: github.event.inputs.distinct_id != ''
        run: echo ${{ github.event.inputs.distinct_id }}
      - name: downloadGithub
        if: github.event.inputs.download == 'github'
        run: echo "DOWNURL=https://github.com/${{ github.repository_owner }}" >> $GITHUB_ENV
        # run: echo "DOWNURL=https://github.com/adedner" >> $GITHUB_ENV
      - name: downloadLund
        if: github.event.inputs.download == 'lund'
        run: |
          echo "DOWNURL=https://gitlab.maths.lu.se/dune" >> $GITHUB_ENV
          echo "FEMPYGITURL=https://gitlab.maths.lu.se/dune/dune-fempy.git" >> $GITHUB_ENV
      - name: printParameters
        run: |
          echo "Workflow parameters"
          echo "Using github branch    : ${GITHUB_REF#refs/heads/}"
          echo "Using log level        : ${{ github.event.inputs.logLevel }}"
          echo "Using download         : ${{ env.DOWNURL }}"
          echo "Using fempy-url        : ${{ env.FEMPYGITURL }}"
          echo "Using dune-core  branch: ${{ github.event.inputs.branch }}"
          echo "Using dune-fem   branch: ${{ github.event.inputs.fembranch }}"
          echo "Using dune-fempy branch: ${{ github.event.inputs.fempybranch }}"
          echo "Run tests: ${{ github.event.inputs.runTests }}"
          echo "upload notebooks: ${{ github.event.inputs.uploadNB }}"
          echo "compile flags:  ${{ github.event.inputs.cxxFlags }}"
          echo "ref: ${{ github.ref }}"
      - name: starting
        uses: actions/checkout@v6
      - name: Test on dune/dune-testpypi and get the run ID
        uses: codex-/return-dispatch@v3.0.2   # v2
        id: return_dispatch
        with:
          token: ${{ secrets.Dispatch_Secret }}
          repo: dune-testpypi
          owner: dune-project
          ref: ${{ github.event.inputs.testingbranch }}
          workflow: testing.yml
          workflow_inputs: '{ "logLevel": "${{ github.event.inputs.logLevel }}", "branch": "${{ github.event.inputs.branch }}", "fembranch": "${{ github.event.inputs.fembranch }}", "download": "${{ env.DOWNURL }}", "runTests": "${{ env.RUNTESTS }}" }'
          # workflow_timeout_seconds: 120
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v2
        with:
          token: ${{ secrets.Dispatch_Secret }}
          repo: dune-testpypi
          owner: dune-project
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 7200
          poll_interval_ms: 5000
      - name: download artifacts from RUN ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.Dispatch_Secret }}
          repo: dune-project/dune-testpypi
          workflow: testing.yml
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          workflow_conclusion: success
          name: packages
          path: dist
          if_no_artifact_found: fail
          # find the latest - might fail...
          # branch: main
          # workflow_search: true
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: dist

  # test packages
  test:
    name: testing tutorial
    env:
      # same for dune and github build, different for lund
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      FEMPYGITURL: 'https://gitlab.dune-project.org/dune-fem/dune-fempy.git'
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        test: [coreA, coreB, extensions]
        # python: [3.9, 3.13] # 3.13 mpi4py not building on macOS (tested 18/05)
        # NOTE: upload of notebook artifacts is only done by one Python job
        #       if changing 3.14 then also remember to change the if
        #       statement in the final step!
        python: ['3.10', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - name: starting
        uses: actions/checkout@v6
      - name: pipPreOrNot
        run: |
          echo "PIPPRE=--pre" >> $GITHUB_ENV
      - name: setup python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: environmentLog
        if: github.event.inputs.logLevel != ''
        run: echo "LOGLEVEL=${{ github.event.inputs.logLevel }}" >> $GITHUB_ENV
      - name: download artifacts
        uses: actions/download-artifact@v8
        # if all packages exist on pypi then no artifacts are uploaded so don't fail
        continue-on-error: true
        with:
          name: packages
          path: dist
      - name: Install dependencies
        run: |
          curl 'https://raw.githubusercontent.com/dune-project/dune-testpypi/main/ossetup' > ossetup
          bash ./ossetup "$RUNNER_OS"
        shell: bash
      - name: Setup venv
        run: |
          # Installing petsc4py into the system does not work due to the
          # change of Python version in the matrix setup - a system
          # petsc4py will only work with the system Python.
          # We will use a conda environment to make sure petsc and petsc4py
          # are recent versions and work with the right Python version - we
          # don't want to compile petsc from scratch to reduce runtime:
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get remove petsc-dev python3-mpi4py python3-ufl python3-petsc4py-real
            wget -qO /tmp/miniforge.sh https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
            bash /tmp/miniforge.sh -b -p $HOME/miniforge
            # export PATH="$HOME/miniforge/bin:$PATH"
            PATH="$HOME/miniforge/bin:$PATH" conda install -y -n base -c conda-forge mamba
            PATH="$HOME/miniforge/bin:$PATH" mamba create -y -n petsc -c conda-forge python=${{ matrix.python }} petsc petsc4py openmpi mpi4py
            source $HOME/miniforge/bin/activate petsc
          fi
          # not using an extra env although the conda setup already has one
          # - might be worth figuring out at some point how to avoid this
          # step with the conda environment
          python3 -m venv --system-site-packages dune-env
          source dune-env/bin/activate
          PYVERS=`python3 --version`
          echo "Selected python version $PYVERS"
          pip3 install --upgrade pip
          pip3 install matplotlib scipy scikit-build pygmsh wheel jupyter jupytext pandas
          pip3 install landlab
          if [ "$RUNNER_OS" == "Linux" ]; then
            pip3 install scikit-umfpack
          else
            pip install mpi4py
            echo "CURRENTLY PETSC4PY AND SCIKIT-UMFPACK IS DISABLED on MACOs due to issues - needs checking"
          fi
        shell: bash
      - name: pip3 install dune modules
        run: |
          if [ -n "${{ github.event.inputs.cxxFlags }}" ]; then
            export CXXFLAGS="${{ github.event.inputs.cxxFlags }}"
          fi
          ls dist
          if [ "$RUNNER_OS" == "Linux" ]; then
            source $HOME/miniforge/bin/activate petsc
            # export PATH="$HOME/miniforge/bin:$PATH"
            export PETSC_DIR="$CONDA_PREFIX"
            export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
            export CPATH="$CONDA_PREFIX/include:$CPATH"
            export PKG_CONFIG_PATH="$CONDA_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
          fi
          source dune-env/bin/activate
          pip3 install extract-version
          python extractreq.py
          cat requirements.txt
          pip install $PIPPRE  -U -v --find-links file://$PWD/dist -r requirements.txt
          pip list
        shell: bash
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v3
        id: cpu-cores
      - name: Set tutorial path
        if: github.event.inputs.download == 'lund'
        run: echo "FEMPYGITURL=https://gitlab.maths.lu.se/dune/dune-fempy.git" >> $GITHUB_ENV
      - name: Run tutorial
        run: |
          set -e
          # env -i HOME="$HOME" PATH="$PATH" /home/dedner/miniforge/bin/python -m pip install --no-cache-dir -vvv --find-links=/tmp/dist dune-fem==2.12.0.3
          if [ "$RUNNER_OS" == "Linux" ]; then
            source $HOME/miniforge/bin/activate petsc
            export PATH="$HOME/miniforge/bin:$PATH"
            export PETSC_DIR="$CONDA_PREFIX"
            export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
            export CPATH="$CONDA_PREFIX/include:$CPATH"
            export PKG_CONFIG_PATH="$CONDA_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
             # change back to 1
            export MAKE_NOTEBOOK=0
          else
            export MAKE_NOTEBOOK=0
          fi
          echo "================================"
          source dune-env/bin/activate
          echo "USING python"
          python --version
          pip list
          export DUNE_LOG_LEVEL=$LOGLEVEL
          export OMP_NUM_THREADS="${{ steps.cpu-cores.outputs.count }}"
          if [ -n "${{ github.event.inputs.cxxFlags }}" ]; then
            export CXXFLAGS="${{ github.event.inputs.cxxFlags }}"
          fi
          export DUNE_SAVE_BUILD="console"
          python -c "from dune.fem import threading; print(f'Default number of threads used {threading.use}')"
          python -c "from dune.generator import builder; builder.initialize()"
          if [ "$RUNNER_OS" == "Linux" ]; then
            python -c "import petsc4py,sys; print(petsc4py.get_include())"
          fi
          which python
          echo "========================"
          echo "========================"
          cd dune-env/.cache/dune-py
          rm CMakeCache.txt
          cmake .
          cd ../../..
          echo "========================"
          echo "========================"
          cat dune-env/.cache/dune-py/CMakeCache.txt
          echo "========================"
          cat dune-env/.cache/dune-py/CMakeFiles/CMakeOutput.log
          echo "========================"
          cat dune-env/.cache/dune-py/CMakeFiles/CMakeError.log
          echo "========================"
          echo "========================"

          git clone --depth 1 -b ${{ github.event.inputs.fempybranch }} ${{ env.FEMPYGITURL }}
          cd dune-fempy/doc
          make clean
           # python ../../run-tutorial.py ${{ matrix.test }} ${{ steps.cpu-cores.outputs.count }} $MAKE_NOTEBOOK  #
          cd ..
          if [ "$MAKE_NOTEBOOK" == "1" ]; then
            mkdir ../notebooks-${{ matrix.test }}
            git status --porcelain | awk 'match($1, "M"){print $2}' > newfiles.txt
            cat newfiles.txt | xargs cp -t ../notebooks-${{ matrix.test }}
            cd ..
          fi
        shell: bash
      - name: Upload Notebook
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.14'
        uses: actions/upload-artifact@v7
        with:
          name: notebooks-${{ matrix.test }}
          path: notebooks-${{ matrix.test }}

  pushnbs:
    name: push notebooks
    needs: test
    if: ${{ github.event.inputs.uploadNB == 'true' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout dune-fem-tutorial
        uses: actions/checkout@v6
        with:
          repository: dune-project/dune-fem-tutorial
          ref: 'tutorial/unstable'
          ssh-key: ${{ secrets.PUSH_TUTORIAL_SSH }}
      - name: setup git config
        run: |
          git config --global user.name "Tutorial Bot"
          git config --global user.email "<>"
          # git config --unset-all http.https://github.com/.extraheader
      - name: Download All Noetbooks
        uses: actions/download-artifact@v8
        with:
          path: notebooks
          pattern: notebooks-*
          merge-multiple: true
      - name: copy to dune-fem-tutorial
        run: |
          # this is run inside dune-fem-tutorial folder
          git rm -r doc
          git commit -m "remove old doc..."
          git clone --depth 1 https://gitlab.dune-project.org/dune-fem/dune-fempy.git
          cp -rL dune-fempy/doc .
          cp conf.py doc
          cp -r notebooks/* doc
          cp conf.py doc
          git add doc
          git commit -m "...add new doc"
          git push -f
      - name: build unstable doc
        uses: codex-/return-dispatch@v3.0.2   # v2
        id: return_dispatch
        with:
          token: ${{ secrets.Dispatch_Secret }}
          repo: dune-fem-tutorial
          owner: dune-project
          ref: main
          workflow: tutorial.yml
          workflow_inputs: '{ "version": "unstable" }'
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v2
        with:
          token: ${{ secrets.Dispatch_Secret }}
          repo: dune-fem-tutorial
          owner: dune-project
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 7200
          poll_interval_ms: 5000
